const botonesSimbolos = [
  { id: 1, simb: "C", big: 0, oper: 1 },
  { id: 2, simb: "7", big: 0, oper: 0 },
  { id: 3, simb: "4", big: 0, oper: 0 },
  { id: 4, simb: "1", big: 0, oper: 0 },
  { id: 5, simb: "0", big: 0, oper: 0 },
  { id: 6, simb: "/", big: 0, oper: 1 },
  { id: 7, simb: "8", big: 0, oper: 0 },
  { id: 8, simb: "5", big: 0, oper: 0 },
  { id: 9, simb: "2", big: 0, oper: 0 },
  { id: 10, simb: ".", big: 0, oper: 1 },
  { id: 11, simb: "X", big: 0, oper: 1 },
  { id: 12, simb: "9", big: 0, oper: 0 },
  { id: 13, simb: "6", big: 0, oper: 0 },
  { id: 14, simb: "3", big: 0, oper: 0 },
  { id: 15, simb: " ", big: 0, oper: 1 },
  { id: 16, simb: "-", big: 0, oper: 1 },
  { id: 17, simb: "+", big: 1, oper: 1 },
  { id: 18, simb: "=", big: 1, oper: 1 },
];
export default botonesSimbolos;
